packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^22.18.0
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest
  "@changesets/cli": ^2.31.0
  "@changesets/changelog-github": ^0.7.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - prettier-plugin-django-templates
