name: Tagged Production Deploys for VS Code

on:
  push:
    tags:
      - "django-vscode-*"

permissions: {}

jobs:
  deploy:
    # prevents this action from running on forks
    if: github.repository == 'EpicAlbin03/django-templates-extension'
    permissions:
      contents: read # to fetch code for packaging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24.x"
          cache: true

      # Ensure everything is compiling
      - run: "vp install --frozen-lockfile"
      - run: "vp run build"

      # Lets us use one-liner JSON manipulations in the package.json files
      - run: "vp install -g json"

      # Setup the environment
      - run: json -I -f packages/django-vscode/package.json -e "this.version=process.env.GITHUB_REF_NAME.replace(/^django-vscode-/, '')"

      # To deploy we need isolated node_modules folders which pnpm won't do because it is a workspace
      # So, remove the workspace
      - run: "rm package.json pnpm-workspace.yaml pnpm-lock.yaml"
      - run: "rm -rf packages/django-vscode/node_modules" # pnpm version of stuff, needs to be removed
      # ... and remove the workspace:* references
      - run: json -I -f packages/django-vscode/package.json -e 'this.dependencies["django-template-language-server"]="*"'

      - run: |
          cd packages/django-vscode
          npm install

          # Just a hard constraint from the vscode marketplace's usage of Azure tokens
          echo "VS Code Marketplace tokens expire once a year, renew AZURE_PAN_TOKEN by logging in to Azure: https://dev.azure.com"

          # Ship it
          npx vsce publish -p $VSCE_TOKEN
          npx ovsx publish -p $OVSX_TOKEN

        env:
          VSCE_TOKEN: ${{ secrets.AZURE_PAN_TOKEN }}
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
